service: notes-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    USERS_TABLE: UsersTable
    NOTES_TABLE: NotesTable   
    JWT_SECRET: supersecret_local

plugins:
  - serverless-offline

functions:
  signup:
    handler: handler/signup.signup
    events:
      - http:
          path: api/user/signup
          method: post

  login:
    handler: handler/login.login
    events:
      - http:
          path: api/user/login
          method: post

  getNotes:
    handler: handler/getNotes.getNotes
    events:
      - http:
          path: api/notes/getNotes
          method: get

  createNote:
    handler: handler/createNote.createNote
    events:
      - http:
          path: api/notes/createNote
          method: post

  updateNote:
    handler: handler/updateNote.updateNote
    events:
      - http:
          path: api/notes/updateNote
          method: put

  deleteNote:
    handler: handler/deleteNote.deleteNote
    events:
      - http:
          path: api/notes/deleteNote
          method: delete

  restoreNote:
    handler: handler/restoreNote.restoreNote
    events:
      - http:
          path: api/notes/restore
          method: post        

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NotesTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

